Emojis:
  - ":heart:, ❤"
  - ":star:, ⭐"
  - ":check:, ✔"
  - ":cross:, ❌"
  - ":lightning:, ⚡"
  - ":music:, ♪"
  - ":snowflake:, ❄"
  - ":pickaxe:, ⛏"
  - ":warning:, ⚠"
  - ":arrow_forward:, ▶"
  - ":arrow_backward:, ◀"
  - ":tm:, ™"
  - ":rtm:, ®"
  - ":sun:, ☀"
  - ":cloud:, ☁"
  - ":infinite:, ∞"
  - ":sword:, ⚔"
  - ":smile:, ☻"
  - ":skull:, ☠"