name: ChatEmojis
version: '1.0'
main: me.blurmit.chatemojis.ChatEmojisSpigot
authors: [ Blurmit ]
description: Allows players to use emojis in chat.
api-version: 1.13
commands:
  emojis:
    description: Main command for ChatEmojis plugin.
    aliases: [ emoji ]